define(function (require) {

    "use strict";

    var $ 			= require('jquery'),
        _ 			= require('underscore'),
        Backbone 	= require('backbone'),
        locale 		= require('i18n!nls/str');

    return Backbone.View.extend({
        className: 'detectionPolicyContent',
        formEl: "form.detectionPolicyPopupForm",
        template: _.template([
            '<div class="padding-l15 padding-r15">',
            '<div class="scroll-height-400">',
            '<div class="icon-subtitle margin-t5"><%=locale.patternExemple.generalInfo%></div>',
            '<div class="border-dotted-all padding-all-5">',
            '<ol>',
            '<li><%=locale.patternExemple.desc1%></li>',
            '<li><%=locale.patternExemple.desc2%></li>',
            '</ol>',
            '</div>',
            '<div class="icon-subtitle"><%=locale.patternExemple.desc3%>룰헤더</div>',
            '<div class="border-dotted-all padding-all-5">',
            '<ol>',
            '<li><%=locale.patternExemple.desc4%></li>',
            '<li><%=locale.patternExemple.desc5%></li>',
            '<li><%=locale.patternExemple.desc6%>',
            '<ol>',
            '<li><%=locale.patternExemple.desc7%></li>',
            '<li><%=locale.patternExemple.desc8%>',
            '<ol>',
            '<li>"tcp"</li>',
            '<li>"udp"</li>',
            '<li>"icmp"</li>',
            '<li> <%=locale.patternExemple.desc9%></li>',
            '</ol>',
            '</li>',
            '<li><%=locale.patternExemple.desc10%>',
            '<ol>',
            '<li><%=locale.patternExemple.desc11%></li>',
            '<li><%=locale.patternExemple.desc12%></li>',
            '<li><%=locale.patternExemple.desc13%></li>',
            '<li> <%=locale.patternExemple.desc14%></li>',
            '<li> ① <%=locale.patternExemple.desc15%> : "any"</li>',
            '<li> ② <%=locale.patternExemple.desc16%> : "x", 1≤x≤0xFFFF </li>',
            '<li> ③ <%=locale.patternExemple.desc17%> : "x:y", 1≤x≤0xFFFF, 1≤y≤0xFFFF, x≤y</li>',
            '<li> - <%=locale.patternExemple.desc18%></li>',
            '<li> - <%=locale.patternExemple.desc19%></li>',
            '<li> - <%=locale.patternExemple.desc20%></li>',
            '<li>       :1000 -> 1~1000 <%=locale.port%> </li>',
            '<li>       1000: -> 1000~65535 <%=locale.port%> </li>',
            '<li>       1000:2000 -> 1000~2000 <%=locale.port%>  </li>',
            '<li> "<%=locale.direction%>"</li>',
            '<li> ① <%=locale.patternExemple.desc21%> : "->" </li>',
            '<li> ② <%=locale.patternExemple.desc22%> : "<>" </li>',
            '<li> <%=locale.patternExemple.desc40%> </li>',
            '</ol>',
            '</li>',
            '</ol>',
            '</li>',
            '</ol>',
            '</div>',
            '<div class="icon-subtitle"><%=locale.patternExemple.desc23%></div>',
            '<div class="border-dotted-all padding-all-5">',
            '<ol>',
            '<li> <%=locale.patternExemple.desc24%></li>',
            '<li> <%=locale.patternExemple.desc25%></li>',
            '<li> <%=locale.patternExemple.desc26%></li>',
            '<li> <%=locale.patternExemple.desc27%></li>',
            '<li> <%=locale.patternExemple.desc28%> </li>',
            '<li> <%=locale.patternExemple.desc29%>.</li>',
            '<ol>',
            '<li> pcre </li>',
            '<div> - <%=locale.patternExemple.desc30%>(perl compatible regular expression) </div>',
            '<div> - <%=locale.patternExemple.desc31%>: pcre:[!](/<regex>/m<delim><regex><delim>)[ismxAEGRUB]"; </div>',
            '<li> content </li>',
            '<div> - <%=locale.patternExemple.desc32%></div>',
            '<div> - <%=locale.patternExemple.desc31%>: content:[!] "<content string>"; </div>',
            '<div> - <%=locale.patternExemple.desc33%></div>',
            '<div> - <%=locale.patternExemple.desc34%></div>',
            '<li> offset </li>',
            '<div> - <%=locale.patternExemple.desc31%>: offset: <number>; </div>',
            '<li> depth </li>',
            '<div> - <%=locale.patternExemple.desc31%>: depth: <number>; </div>',
            '<li>  nocase </li>',
            '<div> - <%=locale.patternExemple.desc31%>: nocase; </div>',
            '<li> distance </li>',
            '<div> - <%=locale.patternExemple.desc31%>: distance: <byte count>; </div>',
            '<li> within </li>',
            '<div> - <%=locale.patternExemple.desc31%>: within: <byte count>; </div>',
            '<li> flags </li>',
            '<div> - tcp flag <%=locale.patternExemple.desc35%> </div>',
            '<div> - <%=locale.patternExemple.desc31%>: flags:[!|*|+]<FSRPAU120>,[,<FSRPAU120>]; </div>',
            '<div> - <%=locale.patternExemple.desc36%></div>',
            '<li> itype </li>',
            '<div> - <%=locale.patternExemple.desc31%>: itype:[<|>]<number>[<><number>]; </div>',
            '<li> icode </li>',
            '<div> - <%=locale.patternExemple.desc31%>: icode:[<|>]<number>[<><number>]; </div>',
            '<li> icmp_id </li>',
            '<div> - <%=locale.patternExemple.desc31%>: icpm_id:<number>; </div>',
            '<li> icmp_seq </li>',
            '<div> - <%=locale.patternExemple.desc31%>: icmp_seq:<number>; </div>',
            '<li> dsize </li>',
            '<div> - <%=locale.patternExemple.desc31%>: dsize: [<>] <number> [<><number>]; </div>',
            '</ol>',
            '</ol>',
            '</div>',
            '<div class="icon-subtitle"><%=locale.patternExemple.desc37%></div>',
            '<div class="border-dotted-all padding-all-5">',
            '<ol>',
            '<li> <%=locale.patternExemple.desc38%></li>',
            '<div> alert tcp any any -> any 80 </div>',
            '<li> <%=locale.patternExemple.desc39%></li>',
            '<div> alert tcp 127.0.0.1/32 -> any 25 </div>',
            '</ol>',
            '</div>',
            '</div>',
            '</div>',
            '</div>'

        ].join('')),
        render: function () {
            this.$el.html(this.template({
                locale: locale
            }));
            return this;
        }
    });
});