#!/bin/bash
#
#
GET_IFNAME=`ip -o -4 route show to default | awk '{print $5}'`
RAND_STR=`head /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c8`
#GET_MAC=`cat /sys/class/net/$(ip route show default | awk '/default/ {print $5}')/address | cut -c 10- | tr -d [:]`
GET_MAC=`cat /sys/class/net/$GET_IFNAME/address | cut -c 10- | tr -d [:]`
NEW_PW=`echo $RAND_STR$GET_MAC | openssl enc -aes-256-cbc -a -salt -k $RAND_STR`
ORIG_PW=
if [ -f /usr/local/mysql/data/db.properties ]; then
ORIG_PW=`cat /usr/local/mysql/data/db.properties | grep password= | cut -b 10-17`'root'$GET_MAC
fi
############################
# Create db properties
############################
echo driver=org.mariadb.jdbc.Driver > /usr/local/mysql/data/db.properties
echo url=jdbc:mariadb://localhost:3306/TESS >> /usr/local/mysql/data/db.properties
echo username=mysql >> /usr/local/mysql/data/db.properties
echo password=$RAND_STR$NEW_PW >> /usr/local/mysql/data/db.properties
echo maxActive=50 >> /usr/local/mysql/data/db.properties
#################################
# Update mysql account password
#################################
echo -e "$RAND_STR$GET_MAC\n$RAND_STR$GET_MAC" | passwd mysql
#################################
# DB password update
#################################
mysql -u root -e "SET PASSWORD FOR 'mysql'@'localhost' = PASSWORD('$RAND_STR$GET_MAC');FLUSH PRIVILEGES;"

