// 최초 개발은 한국어로 한다.
define({
    "root": {
        "validation": {
            "idFail": "아이디는 영문으로 시작하는 6~15자 이내의 문자로 영문, 숫자만 입력 가능합니다.",
            "password": {
                "notEqualRetype": "입력한 두 개의 비밀번호가 서로 일치하지 않습니다.",
                "invalidRule": "비밀번호는 9~20자리를 사용해야 합니다.",
                "invalidMix": "비밀번호는 영문 대문자, 영문 소문자, 숫자, 특수문자를 각 1자 이상 조합하여 사용해야 합니다.",
                "invalidContinue": "비밀번호에 3자 이상의 연속 또는 반복 문자 및 숫자를 사용하실 수 없습니다.",
                "invalidContinueInKeyboard": "비밀번호에 키보드 배열에서 4자 이상의 연속되는 문자 및 숫자를 사용하실 수 없습니다.",
                "equalUsername": "아이디가 포함된 비밀번호는 사용하실 수 없습니다.",
                "invalidRenewal": "기존 비밀번호와 새 비밀번호가 일치합니다.",
                "notInputByteSizes": "20자를 초과 입력할 수 없습니다. 다시 입력 바랍니다.",
                "invalidRenewalReinput":"기존 비밀번호와 같습니다. 비밀번호를 다시 변경해주세요.",
                "notMatchedCurrent":"현재 비밀번호가 일치하지 않습니다.",
                "notConfirmCurrent":"현재 비밀번호가 확인되지 않았습니다."
            },
            "invaildIp": "IP 형식이 잘못되었습니다.",
            "invaildIpv6": "IPv6  형식이 잘못되었습니다.",
            "invaildPort": "포트 형식이 잘못되었습니다.",
            "invaildEmail": "Email 형식이 잘못되었습니다.",
            "invaildTelephone": "전화번호 형식이 잘못되었습니다.",
            "invaildMobile": "휴대폰번호 형식이 잘못되었습니다.",
            "invaildMask": "Ipv4의 Mask 입력 범위는 8~32입니다.",
            "invaildIpv6Mask": "Ipv6의 Mask 입력 범위는 1~128입니다.",
            "invaildMaskAndIp": 'IP의 잘못된 Mask 값입니다.',
            "invaildNumber": '숫자만 입력하십시오.',
            "validateIThresholdRangeNum": "0부터 999999까지 숫자를 입력하세요.",
            "validateIThresholdRangeTime": "0부터 60까지 숫자를 입력하세요.",
            "invaildNumber500Range": "1부터 500까지 숫자를 입력하세요.",
            "invaildNull": "값을 입력하십시오.",
            "invaildFilterNameNull": "필터명을 입력하신 후에 [새 탭에 적용] 버튼을 클릭하십시오. ",
            "invalidMaximumHops": "최대 홉의 범위는 1~100입니다.",
            "invalidTraceRouteTimeout": "대기시간의 범위는 1000~30000입니다.",
            "invaildSignature": "올바른 시그니처가 아닙니다. 다시 입력 바랍니다.",
            "invalidHangeul": "영문자만 가능합니다. 다시 입력 바랍니다.",
            "invaildHangeulAndNumber": "영문자나 하이픈(-)만 가능합니다. 다시 입력 바랍니다.",
            "invalidEmailServer": "영문 숫자로 시작하고 하이픈(-) 콤마(.)만 입력 가능합니다.",
            "invalidServer": "영문 또는 숫자로 시작하고 콤마(.)만 입력 가능합니다.",
            "invalidName":"이름을 입력하십시오.",
            "isDuplicateAttackName": "사용할 수 없는 공격명입니다.",
            "isDuplicatelCode": "사용할 수 없는 코드입니다.",
            "isDuplicateAccountId": "사용할 수 없는 아이디입니다.",
            "isDuplicataValue": "중복된 값입니다.",
            "isDuplicatelCodeValue": "사용자 정의 정책 코드 범위는 1000000 이상 입력 가능합니다.",
            "yaraGroupName": "악성코드 유형명은 영문으로 시작하고 영문, 숫자, _(언더바) 만 가능합니다. 다시 입력해주세요.",
            "detectionGroupName": "공격 유형명은 영문으로 시작하고 영문, 숫자, _(언더바) 만 가능합니다. 다시 입력해주세요.",
            "nameNullValid": "이름은 필수 입력 사항입니다.",
            "duplicateName": "동일한 이름이 이미 등록되어있습니다. 다른 이름으로 입력해 주시기 바랍니다.",
            "periodDate": "분석기간의 시작시간은 종료시간보다 이전 시간이어야 합니다. 다시 선택하시기 바랍니다.",
            "periodMinDate30": "분석기간의 최소 선택 시간은 30분 입니다. 다시 선택하시기 바랍니다.",
            "startEndTimeValid":"시작시간은 종료시간보다 이전 시간이어야 합니다.",
            "reInput": " 다시 입력해주세요.",
            "isDulicateFilterName":"중복된 필터명이 있습니다.",
            "reInputValue":"다시 입력해 주시기 바랍니다.",
            "isDuplicateVsensorName":"동일한 가상센서 이름이 이미 등록되어있습니다. 다른 이름으로 입력해 주시기 바랍니다.",
            "isDuplicateSensorName":"동일한 센서 이름이 이미 등록되어있습니다. 다른 이름으로 입력해 주시기 바랍니다.",
            "isDuplicateNetgroupName":"동일한 네트워크그룹 이름이 이미 등록되어있습니다. 다른 이름으로 입력해 주시기 바랍니다.",
            "isDuplicateNetworkName":"동일한 네트워크명이 이미 등록되어있습니다. 다른 이름으로 입력해 주시기 바랍니다.",
            "names":"이름이 ",
            "description":"설명이 ",
            "sensorSelected":"물리센서를 선택해주세요.",
            "isDuplicatePublicStaticIp":"해당 사설IP와 공인IP는 이미 사용중입니다. 다른 사설IP또는 공인IP를 입력하세요.",
            "isStartIpEndIp":"끝IP는 시작IP보다 커야합니다.",
            "changeSelectedIp":"변경할 IP를 선택해주세요.",
            "selectedDeleteIp":"삭제할 IP를 선택해주세요.",
            "selectedNetwork":"네트워크를 전택해주세요.",
            "ipBlockSelected":"IP블럭 목록에 IP를 추가해주십시오.",
            "networkGroupInsertFailNetwork":"선택가능한 네트워크가 없어 네트워크 그룹을 생성할 수 없습니다.",
            "networkInsertFailVsensor":"선택가능한 가상센서가 없어 네트워크를 생성할 수 없습니다.",
            "insertNetwork":"네트워크를 등록해 주세요.",
            "isVsensorDuplicateRuleNetwork":"해당 가상센서와 연동된 정책 및 네트워크가 있습니다.",
            "isNetworkDuplicateRuleNetGroup":"해당 네트워크와 연동된 정책 또는 상위 그룹이 있습니다.",
            "validDetectiongroupName":"입력된 내용이 없습니다. 공격 유형명을 입력해주세요.",
            "validYaragroupName":"입력된 내용이 없습니다. 악성코드 유형명을 입력해주세요.",
            "noneDeleteDefaultUserGroup":"기본 사용자 정의 유형은 삭제 하실수 없습니다.",
            "isDuplicateData":"중복된 데이터 입니다.",
            "validFildValue":"해당필드의 올바른 값을 입력하세요.",
            "isDuplicateReserve":"중복된 예약명이 있습니다.",
            "validValue":"값이 올바르지 않습니다.",
            "isDuplicatePort":"동일한 포트가 이미 등록되어있습니다.",
            "isDuplicateProtocol":"동일한 프로토콜이 이미 등록되어있습니다.",
            "noneDeleteServiceName":"삭제할 수 없는 서비스명 입니다.",
            "serviceNameNullValid":"서비스명은 필수 입력 사항입니다.",
            "portNullValid":"포트는 필수 입력 사항입니다.",
            "validAccountSelected":"소속 계정을 선택해주세요.",
            "isDuplicateGroupName":"중복된 그룹명이 있습니다.",
            "valueInputValid":"값을 입력하세요",
            "maskRangeValid":"mask의 입력 범위는 8~32입니다.",
            "ipInputNullValid":"IP를 입력하세요",
            "thresholdNumValid":"임계치 입력 형식이 잘못되었습니다.",
            "thresholdValueValid":"임계치 입력값이 잘못되었습니다.",
            "anomaliesApplyTrrgetValid":"적용대상을 선택 시 트래픽임계 또는 이벤트변화를 설정 하셔야 합니다.",
            "anomaliesProfileNonDelete":"해당 프로파일은 이상징후 정책에 적용되었기 때문에 삭제할 수 없습니다.",
            "isDeplicateName":"은(는) 중복된 이름 입니다.",
            "noneDefaultAttackTypeDelete":"기본 사용자 정의 공격유형은 삭제 하실수 없습니다.",
            "selectedFile":"파일을 선택하십시오.",
            "noneImpprtFile":"가져오기 할 수 없는 파일형식입니다.",
            "selectedCsvFile":".csv 형식의 파일을 선택해주세요.",
            "detectionImportSuccess":"정책 가져오기가 정상처리 되었습니다.",
            "detectionImportFail":"정책 가져오기가 실패 되었습니다.",
            "inputErrorMsg":"잘못 입력 하셨습니다. 다시 입력하세요.",
            "dateInputErrorMsg":"현재 시각보다 이후의 시각은 설정하실 수 없습니다.",
            "grapeMinValid":"그래프 최소 조회시간은 30분 이상 입니다.",
            "duplicateSourceIpDestnationIp":"동일한 소스IP와 대상IP가 이미 존재합니다.",
            "nationUpdateFileSelectedValid":"국가정보 업데이트를 위해 파일을 1개 이상 선택해야합니다.",
            "notUpdateFile":"업데이트 할 수 없는 파일형식입니다.",
            "fileTypeSelectedValid":" 형식의 파일을 업로드하세요.",
            "fileImportSelectedValid":"가져오기 할 수 없는 파일형식입니다.",
            "fileUploadSelectedValid":"업로드할 수 없는 파일 형식입니다.",
            "orStr":"또는",
            "patternUpdateFileSeleceedValid":"패턴 업데이트를 위해 파일을 1개 이상 선택해야합니다.",
            "fileUploadPathValid":"파일 업로드 경로가 올바르지 않습니다.",
            "minTrafficMaxTrafficValid":"Min 기준 트래픽은 Max 기준 트래픽 보다 작아야합니다. 다시 입력해주세요.",
            "inputIpNullValid":"추가하고자 하는 IP를 입력하세요.",
            "authIpTwo":"허용 IP 최대 개수는 2개 입니다.",
            "duplicateIp":"등록된 허용 IP 입니다.",
            "duplicateIpMsg":"등록된 IP가 있습니다.",
            "loginIpValid":"로그인 설정 IP는 1개이상 등록 하셔야 합니다.",
            "isDuplicateId":"중복된 아이디가 있습니다.",
            "authIpCount":"허용 IP 최대 개수는 ",
            "isCount":"개 입니다.",
            "deleteReportSelectedValid":"삭제 할 보고서를 하나이상 선택해 주십시오.",
            "vsensorSelectedOneSelectedValid":"가상센서 선택시 가상센서 목록 중 하나이상 선택해야합니다.",
            "networkSelectedOneSelectedValid":"네트워크 선택시 네트워크 목록중 하나이상 선택해야합니다.",
            "countModThresholdValid":"건수변화 위험도별 임계값을 다시입력하세요.",
            "countModSeverityValid":"건수변화 위험도별 최소발생건수가 1건 이상 이어야 합니다.",
            "trafficSeverityValid":"트래픽변화 위험도별 임계값을 다시입력하세요.",
            "trafficSeverityOneInputValid":"트래픽변화 위험도별 최소발생건수가 1건 이상 이어야 합니다.",
            "rankModThresholdValid":"순위변화 위험도별 임계값을 다시입력하세요.",
            "rankModSeverityOneInputValid":"순위변화 위험도별 최소발생건수가 1건 이상 이어야 합니다.",
            "duplicateProtocolTrafficUnit":"이미 추가된 프로토콜, 트래픽단위 항목입니다.",
            "duplicateProtocolPortTrafficUnit":"이미 추가된 프로토콜, 포트, 트래픽단위 항목입니다.",
            "thresholdRangeValid":"임계값 범위가 올바르지 않습니다.",
            "severityThresholValid":"위험도별 임계값을 확인하세요.",
            "deployRuleTargetVsensorSelectedValid":"배포할 정책과 배포대상 가상센서를 선택 해 주세요.",
            "deployRuleSelectedValid":"배포할 정책을 선택 해 주세요.",
            "deployTargetVsesorValid":"배포대상 가상센서를 선택 해 주세요.",
            "isRuleReDeploy":"정책을 재 배포하시겠습니까?",
            "attackNameInput":"공격명을 입력하세요",
            "invalidRiskIndexThresholdRange":"유효하지않은 위험지수 임계치 범위입니다.",
            "invalidRiskWeightRange":"유효하지않은 위험도 가중치 범위입니다.",
            "ruleNameNullValid":"룰 이름은 필수 입력 사항입니다.",
            "ruleNameValueValid":"룰 이름은 영문으로 시작하고, 영문, 숫자 언더바(_)만 입력 가능합니다.",
            "metaNullValid":"meta 정보는 필수 입력사항 입니다.",
            "stringsNullValid":"strings 정보는 필수 입력사항 입니다.",
            "conditionNullValid":"condition 정보는 필수 입력사항 입니다.",
            "dbbackupSelectedValid":"백업할 항목을 선택 하세요.",
            "maintenancePeriodZeroValid":"유지 기간 값은 0보다 커야 합니다.",
            "selectedAddServerValid":"추가하고자 하는 서버를 입력하세요.",
            "duplicateServerAddress":"등록된 서버주소 입니다.",
            "duplicateServerIp":"등록된 서버 IP 입니다.",
            "addServerMaxValid":"서버 추가 개수는 최대 10개입니다.",
            "addSyslogIpInputNullValid":"추가하고자 하는 syslog 서버 IP를 입력하세요.",
            "serverIpMaxValid":"서버 IP는 최대 10개까지만 등록 가능합니다.",
            "ipTypeErrorNotInsertValid":"IP형식이 올바르지않아 추가할 수 없습니다.",
            "nitIpInputNullValid":"NIC과 IP가 모두 입력되어야 합니다.",
            "detectionPolicyThresholdValueSettingValid":"임계값 설정이 잘못 되었습니다. 다음과 같은 형태로 입력하십시오. (최대 100000개/60초)",
            "aliveSensorValid":"활성화중인 센서가 없습니다.",
            "inputValueMaxValueLimitedValid":"입력값이 최대 입력 가능값 보다 큽니다.",
            "inputValueMinValueLimitedValid":"입력값이 최소 입력 가능값 보다 작습니다.",
            "selectedAliveSensorValid":"활성화 된 센서를 선택하셔야 합니다.",
            "idInputNullValid":"아이디를 넣어주십시오.",
            "accountInfoReinputValid":"계정 정보를 다시입력해주십시오.",
            "certificateResistLogin":"인증서가 등록되었습니다. 로그인하십시오.",
            "threatAlertSelectedValid":"시작ThreatCon 과 종료ThreatCon 값이 동일하게 설정 되어 있습니다. 다시 설정 하십시오.",
            "threatAlertDuplicate":"중복된 항목이 있습니다. 다시 설정해 주십시오.",
            "threatAlertNull": "글로벌/로컬위협 설정 정보를 추가하십시오.",
            "numberCommaInput":"숫자와 . 만 입력가능합니다.",
            "invalidRange":"유효하지않는 범위입니다.",
            "length":"길이가",
            "shouldBeSmaller":"보다 작아야 합니다.",
            "inputLimitValidation":"까지 입력가능합니다.",
            "zeroMinusInputValidation":"0 이하는 입력할 수 없습니다.",
            "specialCharecterInputValidation":"특수문자는 사용하실 수 없습니다.",
            "requirdInputValidation":"필수 입력항목입니다.",
            "upperLawLimitValidation":"상한값이 하한값보다 커야합니다.",
            "stringLength":"문자열 길이",
            "exceededValidation":"를 초과 하였습니다.",
            "korLanguageByteValidation":"한글 1자 2byte, 영문 1자 1byte 입니다.",
            "korLanguageInputValidation":"한글만 입력 가능합니다.",
            "metaValidation":"meta 정보에는 \"rule_id\", \"rule_group_id\", \"severity\", \"rType\", \"org_num\" \n문자를 포함할수 없습니다.",
            "timeSyncNtpServer":"표준시간 서버 주소는 IP 형식 주소를 입력하십시오.",
            "diskWarnUsagedValid":"디스크 사용량 삭제는 디스크 사용량 경고 보다 커야 합니다.",
            "backupCompareValidation":"백업 기간 시작일이 종료일보다 작거나 같아야 합니다.",
            "timeSyncServerLength":"표준시간 서버를 1개이상 등록하십시오.",
            "sftpPwdValid":"SFTP 비밀번호를 입력 하십시오.",
            "sftpIdValid":"SFTP 아이디를 입력 하십시오.",
            "isAlphaNumWithUnderscore": '영문, 숫자, _(언더바) 외에 입력할 수 없습니다',
        },
    },
    "en-us": true,
    "ja-jp": true,
});
