// 최초 개발은 한국어로 한다.
define({
	"root": {
		"menu": {
			/* 상위 메뉴 */
			"dashboard": "종합관제",
			"monitor": "실시간 감시",
			"threatAnalysis": "위협분석",
			"intrusionDetectionAnalysis": "침입탐지분석",
			"applicationAnalysis": "어플리케이션분석",
			"fileAnalysis": "파일분석",
			"trafficAnalysis": "트래픽분석",
			"systemStatus": "시스템현황",
			"report": "보고서",
			"securityPolicy": "보안정책",
			"systemSettings": "시스템관리",
			"preferences": "환경설정",
			/* 하위 메뉴 */ 
			"intrusionDetection": "침입탐지",
			"sessionDetection": "세션탐지",
                        "trafficDetection":"IP 모니터링",
			"anomaliesDetection": "이상징후탐지",
			"applicationDetection": "어플리케이션탐지",
			"fileMetaDetection": "파일탐지",
			"systemState": "시스템상태",
			//"traffic": "트래픽",
			"globalThreat": "글로벌위협",
			"localThreat": "로컬위협",
			"anomaliesThreat": "이상징후위협",
			"attack": "공격",
			"attackIp": "공격자IP",
			"victimIp": "피해자IP",
			"victimPort": "피해포트",
			"nationAttack": "국가(공격)",
			"nationAttackerIp": "국가(공격자IP)",
			"institution": "기관",
			"originalLog": "로그분석",
			"detectionLog": "침입탐지",
			"sessionDetectionLog": "세션탐지",
			"application": "어플리케이션",
			"applicationLog": "어플리케이션탐지",
			"fileMetaLog": "파일탐지",
			"correlationAnalysis": "상관분석",
			"protocol": "프로토콜",
			"services": "서비스",
			"frameSize": "프레임 크기",
			"tcpFlag": "TCP플래그",
			"ip": "IP",
			"maliciousTraffic": "유해트래픽",
			"session": "세션",
			"prevention": "예/경보",
			"auditLog": "감사로그",
			"managerState": "시스템상태",
			"sensorState": "센서현황",
			"serviceInfo": "자산현황",
			"reservation": "예약",
			"creation": "생성",
			"search": "조회",
			"intrusionDetectionBatchDeployment": "침입탐지 일괄배포",
			"intrusionDetectionPolicy": "침입탐지",
			"sessionMonitorPolicy": "세션감시",
			"anomaliesDetectionPolicy": "이상징후탐지",
			"hostManagement": "호스트 관리",
			"threatPolicy": "위협수준탐지",
			"threatAlert": "위협수준 예/경보",
			"auditLogPolicy": "감사로그 정책",
			"historyOfChanges": "변경 이력",
			"DBUsage": "DB 사용량",
			//"systemState": "시스템상태",
			"systemConfig": "시스템 설정",
			"manager": "매니저",
			"sensors": "센서",
			"virtualSensors": "가상센서",
			"networkGroup": "네트워크 그룹",
			"network": "네트워크",
			"account": "계정관리",
			"about": "제품정보",
			"refresh":"새로고침",
			"fiveMin": "5분마다",
			"ipRetrieve": "IP조회",
			"attackInfo": "공격정보",		
			//"applicationDetection": "Application 탐지",
			//"fileMetaDetection": "FileMeta 탐지",
			//"application": "Application 검색",
			//"fileMeta": "FileMeta 검색",
			"filterView": "필터뷰 설정",
			"yaraRulePolicy": "악성코드",
			//"applicationLog": "Application Log",
			"yaraRuleBatchDeployment": "악성코드 일괄배포",
                        "detectionPolicyExclude":"탐지예외정책"
		}
	},
	"en-us": true,
        "ja-jp": true,
});
